### ISSUE TITLE
Position of some parts are wrong in JCLPCB

### ISSUE THREAD

**Issue by Cologran** [polpo/picogus#22]
Some position of the parts are wrong in JCLPCB.

Look: 

![Screenshot 2023-11-20 093614](https://github.com/polpo/picogus/assets/72316053/26e65616-4e84-4ac8-b446-990a87d99716)

**Comment by polpo** [comment]
Yes, J8 is way off, probably because the footprint for that part is very large (it encompasses the maximum wavetable module size). The origin of the footprint is correct, but for some reason it gets placed there. That's about the only component that they aren't able to auto-correct the position of. You can move it yourself on that screen before proceeding to the next step. The two 3.5mm connectors and micro-USB connector also are a bit off position-wise and can be tweaked as well. JLC is good about double checking positioning/rotation manually before PCBA orders are put into production, but it's best to align things yourself first.

I could fix the alignment of everything in the CPL file that's checked in, but it'd be an awful lot of trial and error that the component placement step can take care of, and if I update the CPL with the KiCad JLCPCB plugin, I'll have to re-correct the positions.
